title: Historical Data Breaches Archive
description: An archive of historical data breaches with details and sources.

markdown: kramdown
permalink: pretty

url: "https://archive.trace.rip"

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at